name: Post leetcode question to discord channel

on:
  workflow_dispatch:
  schedule:
      - cron:  '0 0 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18'
      - run: go run main.go
        env:
          DISCORD_BOT_TOKEN: ${{secrets.DISCORD_BOT_TOKEN}}
          DISCORD_BOT_ID: ${{secrets.DISCORD_BOT_ID}}
          CHANNEL_ID: ${{secrets.CHANNEL_ID}}
